services:
  - type: web
    name: jobmatch-backend
    runtime: node
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: npm install && npx tsc
    startCommand: node dist/src/db/migrate.js && node dist/src/server.js
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://frontend-nine-omega-72.vercel.app
      - key: ASGARDEO_JWKS_URL
        value: https://api.asgardeo.io/t/orgsacma/oauth2/jwks
      - key: ASGARDEO_ISSUER
        value: https://api.asgardeo.io/t/orgsacma/oauth2/token
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: jobmatch-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: jobmatch-redis
          property: connectionString

  - type: redis
    name: jobmatch-redis
    region: singapore
    plan: free
    maxmemoryPolicy: noeviction
    ipAllowList: []

databases:
  - name: jobmatch-db
    region: singapore
    plan: free
